### ISSUE TITLE
Chemins parfois incorrects

### ISSUE THREAD

**Issue by DashaT0635413** [DashaTaillefer/TP2#3]
Certains liens sur les pages html ne sont pas toujours correctement indiqués, ce qui fait qu'ils ne fonctionnent seulement quand on utilise l'extension "Live Server" de Visual Studio Code, mais pas quand on l'ouvre directement dans le navigateur à partir de l'explorateur de fichiers. 

Exemples: une des photos sur la page index.html et les liens vers le CSS des pages contact.html et carrieres.html.

**Comment by DashaTaillefer** [comment]
C'est arrangé. Voir le dernier commit effectué sur "main".
